.\" Manpage for dmenu_eo
.\"
.\" Copyright(c) 2018 Zachary Matthews.
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <https://www.gnu.org/licenses/>.

.TH DMENU_EO 1 "17 September 2018" "0.1" "dmenu_eo man page"
.SH NAME
dmenu_eo \- browse EO,EN definitions supported dictionaries
.SH SYNOPSIS
.BR dmenu_eo " [\fIOPTION\fP]"
.SH DESCRIPTION
.B dmenu_eo
is a program, which is used to browse Esperanto to English definitions from ESPDIC and O'Conner and Hayes English-Esperanto dictionary, with support for both the X-system and the H-system.
.SH OPTIONS
.TP
.BR \-d ", " \-\-dict ", " \-\-vortaro "=\fIDICT\fP"
Specify the dictionary, DICT, which will be opened(See DICTIONARIES section)
.TP
.BR \-\-help ", " \-\-helpi
Display the help message
.TP
.BR \-h ", " \-\-hsystem ", " \-\-hsistemo
Add H-system entries to dictionary(during rebuild)
.TP
.BR \-m ", " \-\-menu ", " \-\-menuo
Select dictionary to browse from a menu
.TP
.BR \-r ", " \-\-rebuild ", " \-\-rekonstrui
Rebuild dictionary with specified systems
.TP
.BR \-x ", " \-\-xsystem ", " \-\-xsistemo
Add X-system entries to dictionary(during rebuild)
.SH DICTIONARIES
.TP
.BR ES
ESPDIC
.TP
.BR OC
O'Connor and Hayes Dictionary
.TP
.BR KO ""
Komputeko Dictionary
.SH BUGS
No known bugs.
.SH AUTHOR
Zachary Matthews (zacharymatt5@gmail.com)
